# Site settings
title: Roland Croft
baseurl: ""
url: "https://RolandCroft.github.io"
google_analytics: UA-175517802-1'

# Author
author:
  name: Roland Croft
  desc: Researcher: Software Engineering, Data Science and AI
  email: roland.croft@gmail.com
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: RolandCroft
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/rolandcroft/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: CroftRoland
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
